### PR TITLE
wait for transition only if needed

### LINKED ISSUE #101: Do not wait for transitionEnd if transitionStart is not fired
In most cases tests are run without any css which does not work with the current implementation.
If the browser supports CSS animations, it is waiting for the `transitionEnd` event regardless if transitions are started or not.

/cc @ajafff

### PR DESCRIPTION
**Pull request by CSchulz**
fixes #101

### CODE REVIEW

**Comment by slehkodukh** [comment]
@robinparisi When we can expetc merge for this PR?

**Comment by robinparisi** [comment]
Hi @CSchulz @slehkodukh,

Could you provide me a way to test #101 because the actual code of this PR breaks the onOpen callback (the callback is called immediately and no longer respects the transition duration).

**Comment by slehkodukh** [comment]
> Hi @CSchulz @slehkodukh,
> 
> Could you provide me a way to test #101 because the actual code of this PR breaks the onOpen callback (the callback is called immediately and no longer respects the transition duration).
as a short way you can disable styles and try to open modal. onOpen will not execute

**Comment by CSchulz** [comment]
It seems there is an issue with the `transitionstart` event in Chrome. It is not fired.

Furthermore Firefox needs a delay of 12 ms, but it works with the `transitionstart` event.

**Pull request closed without merging**
