### PR TITLE
Added closing method options [button, overlay, escape]

### PR DESCRIPTION
**Pull request by agustinsaldias**
Added the above option based on #38 feedback, to optionally force closing the modal using the close button **only**. 

It's off by default.

### CODE REVIEW

**Comment by robinparisi** [comment]
Hi agustindaldias,

Thanks a lot for the PR. I’m currently working on a convenient way to disable close and to remove close button (some people are also asking for this) so I will try to come up with a solution that is right for everyone.

I keep your PR at hand.Thanks!

**Comment by agustinsaldias** [comment]
Hey @robinparisi , I was thinking of doing it with a closeMethod option (none, both, button, backdrop), which I already did locally, but I'm guessing you're trying to achieve more of a 'add-on-y' way to do it maybe? If you want, I can tidy this up and push up the closeMethod one.

**Comment by robinparisi** [comment]
Indeed, closeMethod option with multiple values is a good idea, I would rather choose an array to go with it:

`closeMethod: ['escape', 'overlay', 'button'] // values by default`

ex for removing close button:

`closeMethod: ['escape', 'overlay'] // override default value`

**Comment by agustinsaldias** [comment]
That's definitely a better approach. 

I've made a couple changes here and there, let me know if this is along the lines of what you had in mind :)

**Comment by robinparisi** [comment]
Hi @agustinsaldias,

Your pull request is now merge into master and ready to be deployed on v0.10.0. Thanks a lot!

**Pull request merged**
